[build]
  publish = "."
  command = "npm install"
  functions = "netlify/functions"

[functions]
  directory = "netlify/functions"
  included_files = ["data/default-products.csv", "default-products.csv"]
  node_bundler = "esbuild"
